name: pytest

on:
  push:
    branches:
      - feature/*
      - operations/actions/*

jobs:
  pytest:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f test.requirements.txt ]; then pip install -r test.requirements.txt; fi
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Test with pytest
        run: |
          pytest
      - name: Expose Coverage Results
        run: |
          python3 utils/btr.py
          echo "covreport=$(cat test-results.json)" >> $GITHUB_ENV
      - name: Ping me On Discord
        uses: kha7iq/pingme-action@v1
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          DISCORD_CHANNELS: ${{ secrets.DISCORD_CHANNELS }}
          DISCORD_MSG_TITLE: '>>> Action Result: pytest #${{ github.run_number }} - ${{ needs.pytest.result }}'
          DISCORD_MESSAGE: 'TRIGGER: ${{ github.event_name }} | BRANCH: ${{ github.ref_name }} | REPO: ${{ github.server_url }}/${{ github.repository }} | COVERAGE: ${{ env.covreport }}'
        with:
          service: discord
